### ISSUE TITLE
Unicode errors in benches?

### ISSUE THREAD

**Issue by edent** [BathHacked/banes-geographic-data#2]
`Voghinder¿Singh Roudh`
https://github.com/BathHacked/banes-geographic-data/blob/master/banes_park_seats_and_benches.geojson?short_path=e25f722#L323

`'Jeanette Barr ¿Be happy and enjoy life¿ '`
https://github.com/BathHacked/banes-geographic-data/blob/master/banes_park_seats_and_benches.geojson?short_path=e25f722#L349

`'Dedicated to Inga Leskanicova ¿ ved rozumies ¿'`
https://github.com/BathHacked/banes-geographic-data/blob/master/banes_park_seats_and_benches.geojson?short_path=e25f722#L153

**Comment by markowen** [comment]
Apologies for the delay in replying to this. The error seems to be in the source files supplied to us.

A refresh of files is in the pipeline & I hope that this will be fixed during the refresh.

**Comment by markowen** [comment]
This file has now been updated. The issue persists in the source data but broken unicode characters should be removed.

There is now an issue with the unique ids for the 2 new benches added since the last release.

I'll try to discuss the issues with BANES staff when possible.

**Comment by edent** [comment]
Thanks! We now have lots of photos of the benches - if you'd like to reuse some of that data?
https://openbenches.org/#51.38742/-2.365494/14
